### ISSUE TITLE
[Question] Why did you remove BTRFS guide fedora from your website.

### ISSUE THREAD

**Issue by ShrirajHegde** [wmutschl/timeshift#1]
Hello, a bit of off topic, your website had great instructions on setting up timeshift BTRFS by renaming subvolume names, After  a long time I went to look it up, and I see it's not there. What is the reason? Is the method not working or giving any problems??

I have been using the same setup from my fedora 33 installation, and it's working flawlessly. 

Also, If you still use Fedora, how do you handle snapshots of boot partition? Do you have any advice on moving `/boot` into `@` so that everything is backed up?

**Comment by wmutschl** [comment]
Hi, sorry I moved the guide to a new homepage https://mutschler.dev.
I do plan to post a video on two ways to make timeshift work with Fedora:
1. use my fork of timeshift
2. rename the subvolumes.

Watch out for the new guides and video :-)
